"""add_chat_usage_platform_messages

Revision ID: cbbc170b5f44
Revises: add_uq_application_user_job
Create Date: 2026-04-06 18:46:10.360769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'cbbc170b5f44'
down_revision: Union[str, None] = 'add_uq_application_user_job'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("DROP INDEX IF EXISTS ix_apscheduler_jobs_next_run_time"))
    op.execute(text("DROP TABLE IF EXISTS apscheduler_jobs"))
    op.execute(
        text(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'uq_application_user_job'
                ) THEN
                    ALTER TABLE applications
                    ADD CONSTRAINT uq_application_user_job
                    UNIQUE (user_id, job_id);
                END IF;
            END
            $$;
            """
        )
    )
    op.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS chat_messages (
                id VARCHAR(36) PRIMARY KEY,
                user_id VARCHAR(36) NOT NULL,
                role VARCHAR(20) NOT NULL,
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ DEFAULT now()
            );
            """
        )
    )
    op.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS chat_usage (
                id VARCHAR(36) PRIMARY KEY,
                user_id VARCHAR(36) NOT NULL,
                month VARCHAR(7) NOT NULL,
                message_count INTEGER NOT NULL DEFAULT 0
            );
            """
        )
    )
    op.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS platform_messages (
                id VARCHAR(36) PRIMARY KEY,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                user_id VARCHAR(36) NOT NULL,
                platform VARCHAR(50) NOT NULL,
                external_id VARCHAR(100),
                sender_name VARCHAR(255),
                sender_email VARCHAR(255),
                subject VARCHAR(500),
                content TEXT NOT NULL,
                is_important BOOLEAN NOT NULL DEFAULT false,
                importance_keywords VARCHAR(255),
                status VARCHAR(20) NOT NULL DEFAULT 'unread',
                received_at TIMESTAMPTZ
            );
            """
        )
    )
    op.execute(text("DROP INDEX IF EXISTS idx_chat_messages_created"))
    op.execute(text("DROP INDEX IF EXISTS idx_chat_messages_user"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_chat_messages_id ON chat_messages (id)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_chat_messages_user_id ON chat_messages (user_id)"))

    op.execute(text("DROP INDEX IF EXISTS idx_chat_usage_month"))
    op.execute(text("DROP INDEX IF EXISTS idx_chat_usage_user"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_chat_usage_id ON chat_usage (id)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_chat_usage_month ON chat_usage (month)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_chat_usage_user_id ON chat_usage (user_id)"))

    op.execute(text("DROP INDEX IF EXISTS ix_job_analyses_priority_score"))

    op.execute(text("DROP INDEX IF EXISTS idx_pm_external"))
    op.execute(text("DROP INDEX IF EXISTS idx_pm_important"))
    op.execute(text("DROP INDEX IF EXISTS idx_pm_platform"))
    op.execute(text("DROP INDEX IF EXISTS idx_pm_received"))
    op.execute(text("DROP INDEX IF EXISTS idx_pm_status"))
    op.execute(text("DROP INDEX IF EXISTS idx_pm_user"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_platform_messages_created_at ON platform_messages (created_at)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_platform_messages_external_id ON platform_messages (external_id)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_platform_messages_id ON platform_messages (id)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_platform_messages_is_important ON platform_messages (is_important)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_platform_messages_platform ON platform_messages (platform)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_platform_messages_received_at ON platform_messages (received_at)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_platform_messages_status ON platform_messages (status)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_platform_messages_user_id ON platform_messages (user_id)"))
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('user_profiles', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('user_profiles', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user_profiles', 'linkedin_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('user_profiles', 'github_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('user_profiles', 'portfolio_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('user_profiles', 'experience_level',
               existing_type=sa.TEXT(),
               type_=sa.Enum('entry', 'mid', 'senior', name='experiencelevel'),
               nullable=False,
               existing_server_default=sa.text("'entry'"))
    op.alter_column('user_profiles', 'desired_roles',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'desired_locations',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'open_to_remote',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'open_to_hybrid',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'min_salary',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_profiles', 'preferred_company_size',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'preferred_industries',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'avoid_companies',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'education',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'work_experience',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'projects',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'certifications',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'awards',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'publications',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'auto_apply_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_profiles', 'auto_apply_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(75)'))
    op.alter_column('user_profiles', 'auto_apply_daily_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(10)'))
    op.alter_column('user_profiles', 'require_apply_approval',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_new_jobs',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_applications',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_interviews',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_via_telegram',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_via_email',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'telegram_chat_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('user_profiles', 'notification_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user_profiles', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('user_profiles', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('user_profiles', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_user_profiles_created_at ON user_profiles (created_at)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_user_profiles_id ON user_profiles (id)"))
    op.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS ix_user_profiles_user_id ON user_profiles (user_id)"))
    op.execute(text("ALTER TABLE IF EXISTS user_sessions ALTER COLUMN last_used_at TYPE TIMESTAMP WITH TIME ZONE"))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'last_login_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'deleted_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_users_created_at ON users (created_at)"))
    op.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)"))
    op.execute(text("CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.execute(text("ALTER TABLE IF EXISTS user_sessions ALTER COLUMN last_used_at TYPE TIMESTAMP"))
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_created_at'), table_name='user_profiles')
    op.alter_column('user_profiles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user_profiles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user_profiles', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user_profiles', 'notification_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'telegram_chat_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'notify_via_email',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_via_telegram',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_interviews',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_applications',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'notify_new_jobs',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'require_apply_approval',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'auto_apply_daily_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(10)'))
    op.alter_column('user_profiles', 'auto_apply_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(75)'))
    op.alter_column('user_profiles', 'auto_apply_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_profiles', 'publications',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'awards',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'certifications',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'projects',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'work_experience',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'education',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'avoid_companies',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'preferred_industries',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'preferred_company_size',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'min_salary',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_profiles', 'open_to_hybrid',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'open_to_remote',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_profiles', 'desired_locations',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'desired_roles',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('user_profiles', 'experience_level',
               existing_type=sa.Enum('entry', 'mid', 'senior', name='experiencelevel'),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'entry'"))
    op.alter_column('user_profiles', 'portfolio_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'github_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'linkedin_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'platform_messages', type_='foreignkey')
    op.drop_index(op.f('ix_platform_messages_user_id'), table_name='platform_messages')
    op.drop_index(op.f('ix_platform_messages_status'), table_name='platform_messages')
    op.drop_index(op.f('ix_platform_messages_received_at'), table_name='platform_messages')
    op.drop_index(op.f('ix_platform_messages_platform'), table_name='platform_messages')
    op.drop_index(op.f('ix_platform_messages_is_important'), table_name='platform_messages')
    op.drop_index(op.f('ix_platform_messages_id'), table_name='platform_messages')
    op.drop_index(op.f('ix_platform_messages_external_id'), table_name='platform_messages')
    op.drop_index(op.f('ix_platform_messages_created_at'), table_name='platform_messages')
    op.create_index('idx_pm_user', 'platform_messages', ['user_id'], unique=False)
    op.create_index('idx_pm_status', 'platform_messages', ['status'], unique=False)
    op.create_index('idx_pm_received', 'platform_messages', ['received_at'], unique=False)
    op.create_index('idx_pm_platform', 'platform_messages', ['platform'], unique=False)
    op.create_index('idx_pm_important', 'platform_messages', ['is_important'], unique=False)
    op.create_index('idx_pm_external', 'platform_messages', ['external_id'], unique=False)
    op.alter_column('platform_messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('platform_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('platform_messages', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('platform_messages', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unread'"))
    op.alter_column('platform_messages', 'is_important',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_job_analyses_priority_score', 'job_analyses', ['priority_score'], unique=False)
    op.drop_index(op.f('ix_chat_usage_user_id'), table_name='chat_usage')
    op.drop_index(op.f('ix_chat_usage_month'), table_name='chat_usage')
    op.drop_index(op.f('ix_chat_usage_id'), table_name='chat_usage')
    op.create_index('idx_chat_usage_user', 'chat_usage', ['user_id'], unique=False)
    op.create_index('idx_chat_usage_month', 'chat_usage', ['month'], unique=False)
    op.alter_column('chat_usage', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.create_index('idx_chat_messages_user', 'chat_messages', ['user_id'], unique=False)
    op.create_index('idx_chat_messages_created', 'chat_messages', ['created_at'], unique=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('chat_messages', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_application_user_job', 'applications', type_='unique')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
