export const UNIVERSAL_SKILLS: string[] = [
  "AB Testing", "Accessibility", "Accounting", "Active Directory", "Adobe Illustrator", "Adobe Photoshop",
  "Adobe XD", "Agile", "Airflow", "AJAX", "Algorithm Design", "Ansible", "Apache", "Apollo GraphQL",
  "App Store Optimization", "ArcGIS", "ARM", "Artificial Intelligence", "ASP.NET", "Assembly", "Astro",
  "Atlassian", "Audio Processing", "Audit", "Auth0", "AutoCAD", "Automation", "AWS", "Azure",
  "Bash", "BigQuery", "Biostatistics", "Bitbucket", "Blender", "Blockchain", "Bootstrap",
  "Browser Testing", "Business Analysis", "C", "C#", "C++", "Canva", "Cassandra", "Celery",
  "Chakra UI", "Change Management", "Chart.js", "CI/CD", "Cinemachine", "CircleCI", "Clean Architecture",
  "Cloud Architecture", "Cloud Computing", "Cloudflare", "CMake", "CNC", "COBOL", "Cocoa", "Communication",
  "Computer Vision", "Confluence", "Content Strategy", "Contract Testing", "Control Systems", "Cosmos DB",
  "CPP", "CRM", "Cryptography", "CSS", "CUDA", "Cypress", "Data Analysis", "Data Engineering",
  "Data Governance", "Data Modeling", "Data Science", "Data Structures", "Data Visualization", "Datadog",
  "DAX", "dbt", "Deep Learning", "Deno", "Design Patterns", "DevOps", "Django", "Django REST Framework",
  "DNS", "Docker", "Domain Driven Design", "DynamoDB", "Edge Computing", "Elasticsearch", "Electron",
  "Elixir", "Embedded Systems", "Ember.js", "Entity Framework", "ETL", "Excel", "Express.js",
  "FastAPI", "Feature Engineering", "Figma", "Firebase", "Flask", "Flink", "Flutter", "Flux",
  "Fortran", "Framer Motion", "Fraud Detection", "Functional Programming", "GCP", "Generative AI", "Git",
  "GitHub", "GitHub Actions", "GitLab", "GitLab CI", "Golang", "Good Clinical Practice", "Go", "Grafana",
  "GraphQL", "gRPC", "Groovy", "Hadoop", "HashiCorp Vault", "Helm", "Heroku", "Hexagonal Architecture",
  "HLSL", "HTML", "HTTP", "Hugging Face", "IAM", "Image Processing", "Incident Response", "InfluxDB",
  "Information Security", "Infrastructure as Code", "Integration Testing", "Interpersonal Skills", "iOS",
  "Istio", "Java", "JavaScript", "Jenkins", "Jest", "Jira", "JPA", "JSON", "Julia", "JUnit",
  "Kafka", "Kanban", "Keras", "Kotlin", "Kubernetes", "LabVIEW", "LangChain", "Laravel", "LaTeX",
  "Leadership", "Lean", "Linux", "LlamaIndex", "Load Testing", "Logstash", "Lua", "Machine Learning",
  "Magento", "MariaDB", "Mathematics", "Matlab", "Matplotlib", "Maven", "Mercurial", "Microservices",
  "MLOps", "MobX", "Model Deployment", "MongoDB", "Monitoring", "Motion Design", "MQTT", "MS SQL Server",
  "Multithreading", "MySQL", "Natural Language Processing", "Neo4j", "NestJS", "Netlify", "Network Security",
  "Networking", "Next.js", "Nginx", "NLP", "NoSQL", "Node.js", "NumPy", "Nuxt.js", "Objective-C",
  "Observability", "OAuth", "OCI", "Office 365", "OpenAPI", "OpenCV", "OpenGL", "OpenShift", "Pandas",
  "Parallel Computing", "Penetration Testing", "Performance Optimization", "Perl", "Photoshop", "PHP",
  "Pinecone", "Playwright", "Plotly", "PostgreSQL", "Power BI", "Predictive Analytics", "Problem Solving",
  "Product Management", "Prometheus", "Protocol Buffers", "Prototyping", "Puppeteer", "PySpark", "PyTorch",
  "Python", "Qlik", "Quantum Computing", "R", "RabbitMQ", "React", "React Native", "React Query",
  "Real-time Systems", "Redis", "Redux", "Regression Testing", "Render", "REST APIs", "Revit", "Risk Management",
  "Robotics", "Rollup", "ROS", "Ruby", "Ruby on Rails", "Rust", "S3", "SaaS", "Salesforce", "SAP",
  "Sass", "Scala", "Scikit-learn", "SCM", "Scrum", "Selenium", "Semantic Search", "SEO", "Serverless",
  "ServiceNow", "Shell Scripting", "Sketch", "Sklearn", "Slack API", "Snowflake", "Socket.IO", "Solidity",
  "SolidJS", "SonarQube", "Spark", "Spring", "Spring Boot", "SQL", "SQLite", "SRE", "SSO", "Storybook",
  "Strategic Planning", "Stripe", "Svelte", "SvelteKit", "Swagger", "Swift", "System Design", "Tableau",
  "Tailwind CSS", "TanStack Query", "Teamwork", "TensorFlow", "Terraform", "Test Automation", "TDD",
  "Three.js", "Time Series", "TypeScript", "UI Design", "Unity", "Unreal Engine", "Unix", "UX Design",
  "Vagrant", "Vault", "Vector Databases", "Vercel", "Version Control", "VHDL", "Video Editing", "Vim",
  "Visual Studio", "Vitest", "VMware", "Vue.js", "Web3", "WebAssembly", "WebRTC", "Webpack", "WebSockets",
  "Windows", "Wireframing", "WordPress", "Xamarin", "XGBoost", "XML", "YAML", "Yii", "Zig", "Zustand",
  "2D Animation", "3D Modeling", "Accounts Payable", "Accounts Receivable", "Ad Operations", "Affiliate Marketing",
  "Analog Circuits", "Android", "Angular", "Ant Design", "Apex", "Applied Statistics", "ArangoDB", "Arduino",
  "ASIC Design", "Audit Analytics", "B2B Sales", "B2C Marketing", "Backbone.js", "Business Development",
  "Campaign Management", "Capital Markets", "Clinical Data Management", "Client Management", "Compliance", "Content Writing",
  "Copywriting", "Cost Accounting", "Customer Success", "Data Annotation", "Data Cleaning", "Data Warehousing",
  "Demand Generation", "Digital Marketing", "Distributed Systems", "E-commerce", "EHS", "Email Marketing",
  "Embedded C", "End-to-End Testing", "Engineering Management", "ETABS", "Event Marketing", "Financial Analysis",
  "Financial Modeling", "FlutterFlow", "FPGA", "Game Design", "Google Ads", "Google Analytics", "HubSpot",
  "HVAC", "Industrial Engineering", "Insurance", "Inventory Management", "ITIL", "Key Account Management",
  "KYC", "Lean Six Sigma", "Logistics", "Manufacturing", "Market Research", "Mechanical Design", "Medical Coding",
  "MERN Stack", "Meta Ads", "Mobile Testing", "Negotiation", "Operations Management", "PCB Design", "People Management",
  "Pipeline Management", "Portfolio Management", "Program Management", "Public Relations", "Quality Assurance", "Recruiting",
  "Requirements Gathering", "Revenue Operations", "Sales Operations", "Scrapy", "SEM", "Social Media Marketing",
  "Solution Architecture", "SPSS", "Stakeholder Management", "Supply Chain Management", "Technical Writing", "Telecommunications",
  "Test Planning", "Trade Compliance", "UAT", "Unity 3D", "Urban Planning", "User Research", "Video Production",
  "Virtualization", "Web Scraping", "WPF", "Zendesk", "Zero Trust", "Zoho CRM",
];
