"use client";
import React, { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { coverLettersApi, jobsApi } from "@/lib/api";
import { useSubscription } from "@/lib/subscription";
import { Sparkles, FileText, Send, Wand2, ArrowRight, BookOpen, Clock, Crown, Download, Eye, Trash2, Plus, X , Loader2} from "lucide-react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

interface CoverLetter {
  id: string;
  job_id: string;
  job_title?: string;
  company_name?: string;
  tone: string;
  content: string;
  status: string;
  created_at: string;
}

interface Job {
  id: string;
  title: string;
  company_name: string;
}

export default function CoverLettersPage() {
  const { canAccess } = useSubscription();
  const qc = useQueryClient();
  const [showGenerate, setShowGenerate] = useState(false);
  const [selectedJob, setSelectedJob] = useState("");
  const [selectedTone, setSelectedTone] = useState("professional");

  const { data: letters, isLoading } = useQuery({
    queryKey: ["cover-letters"],
    queryFn: () => coverLettersApi.list().then((r) => r.data),
  });

  const { data: jobs } = useQuery({
    queryKey: ["jobs-select"],
    queryFn: () => jobsApi.list({ page: 1, page_size: 50 }).then((r) => r.data.items || []),
    enabled: canAccess("cover_letters"),
  });

  const generateMutation = useMutation({
    mutationFn: (data: { job_id: string; tone: string }) => coverLettersApi.generate(data),
    onSuccess: () => {
      toast.success("Cover letter generation started");
      setShowGenerate(false);
      qc.invalidateQueries({ queryKey: ["cover-letters"] });
    },
    onError: () => {
      toast.error("Failed to start generation");
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => coverLettersApi.delete(id),
    onSuccess: () => {
      toast.success("Cover letter deleted");
      qc.invalidateQueries({ queryKey: ["cover-letters"] });
    },
  });

  const handleGenerate = () => {
    if (!selectedJob) {
      toast.error("Please select a job");
      return;
    }
    generateMutation.mutate({ job_id: selectedJob, tone: selectedTone });
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr) return "Unknown";
    const date = new Date(dateStr);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    if (diffHours < 1) return "Just now";
    if (diffHours < 24) return `${diffHours}h ago`;
    const diffDays = Math.floor(diffHours / 24);
    if (diffDays === 1) return "Yesterday";
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  };

  const tones = [
    { value: "professional", label: "Professional", desc: "Formal & corporate" },
    { value: "casual", label: "Casual", desc: "Friendly & relaxed" },
    { value: "founder", label: "Founder-focused", desc: "Entrepreneurial & bold" },
    { value: "enthusiastic", label: "Enthusiastic", desc: "Energetic & positive" },
  ];

  return (
    <div className="dash-page max-w-6xl">
      <div className="flex items-center justify-between gap-4 mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-[#242424] border border-white/[0.08] rounded-lg">
            <BookOpen className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">AI Cover Letters</h1>
            <p className="text-sm text-zinc-400 mt-1">Personalized, job-specific cover letters generated by LLaMA-70B.</p>
          </div>
        </div>
        {canAccess("cover_letters") && (
          <button 
            onClick={() => setShowGenerate(true)}
            className="px-4 py-2 bg-white text-black rounded-lg text-sm font-bold hover:bg-gray-200 transition-all flex items-center gap-2"
          >
            <Wand2 className="w-4 h-4" />
            Generate New Letter
          </button>
        )}
      </div>

      {/* Generate Modal */}
      {showGenerate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
          <div className="bg-[#111118] border border-[#1C1C24] p-8 w-full max-w-md rounded-2xl shadow-2xl">
            <div className="flex items-center justify-between mb-8">
              <h3 className="font-bold text-xl text-white">Generate Cover Letter</h3>
              <button onClick={() => setShowGenerate(false)} className="p-2 hover:bg-[#1C1C24] rounded-lg transition-colors">
                <X className="w-6 h-6 text-[#A1A1AA]" />
              </button>
            </div>
            
            <div className="space-y-6">
              <div>
                <label className="text-xs font-bold text-[#A1A1AA] uppercase tracking-widest mb-2 block">Select Job</label>
                <select 
                  value={selectedJob}
                  onChange={(e) => setSelectedJob(e.target.value)}
                  className="w-full p-3 bg-[#0B0B0F] border border-[#1C1C24] rounded-xl text-white outline-none focus:border-white transition-all shadow-inner"
                >
                  <option value="">Choose a job...</option>
                  {jobs?.map((job: Job) => (
                    <option key={job.id} value={job.id}>
                      {job.title} at {job.company_name}
                    </option>
                  ))}
                </select>
              </div>
              
              <div>
                <label className="text-xs font-bold text-[#A1A1AA] uppercase tracking-widest mb-2 block">Tone</label>
                <div className="grid grid-cols-2 gap-3">
                  {tones.map((tone) => (
                    <button
                      key={tone.value}
                      onClick={() => setSelectedTone(tone.value)}
                      className={cn(
                        "p-3 rounded-xl border text-left text-sm transition-all shadow-sm",
                        selectedTone === tone.value 
                          ? "bg-white border-white text-black" 
                          : "bg-[#0B0B0F] border-[#1C1C24] text-[#A1A1AA] hover:border-gray-500"
                      )}
                    >
                      <div className="font-bold">{tone.label}</div>
                      <div className={cn("text-[10px]", selectedTone === tone.value ? "text-black/60" : "text-[#A1A1AA]")}>{tone.desc}</div>
                    </button>
                  ))}
                </div>
              </div>
              
              <button 
                onClick={handleGenerate}
                disabled={generateMutation.isPending || !selectedJob}
                className="w-full py-4 bg-white text-black rounded-xl font-bold disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg hover:bg-gray-200 transition-all uppercase tracking-widest text-xs"
              >
                {generateMutation.isPending ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Wand2 className="w-4 h-4" />
                )}
                Generate Letter
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="grid lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <div className="dash-card overflow-hidden">
            <div className="p-4 border-b border-zinc-800 bg-[#161616] flex items-center justify-between">
              <h3 className="font-semibold flex items-center gap-2 text-white">
                <Clock className="w-4 h-4 text-white" />
                Your Cover Letters
              </h3>
              <span className="text-xs text-[#A1A1AA] uppercase tracking-widest">{letters?.length || 0} letters</span>
            </div>
            {isLoading ? (
              <div className="p-12 text-center">
                <Loader2 className="w-6 h-6 text-white animate-spin mx-auto" />
              </div>
            ) : letters && letters.length > 0 ? (
              <div className="divide-y divide-[#262626]">
                {letters.map((letter: CoverLetter) => (
                  <div key={letter.id} className="p-4 hover:bg-[#161616] transition-all group">
                    <div className="flex items-start justify-between mb-4">
                      <div className="flex items-center gap-4">
                        <div className="w-10 h-10 rounded-lg bg-[#161616] border border-zinc-800 flex items-center justify-center">
                          <FileText className="w-5 h-5 text-white" />
                        </div>
                        <div>
                          <h4 className="font-bold text-lg text-white">{letter.job_title || "Job Application"}</h4>
                          <p className="text-sm text-[#A1A1AA] font-medium">{letter.company_name || "Company"} • {formatDate(letter.created_at)}</p>
                        </div>
                      </div>
                      <span className={cn(
                        "px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest border",
                        letter.status === "completed" ? "bg-emerald-500/10 text-emerald-500 border-emerald-500/20" : "bg-amber-500/10 text-amber-500 border-amber-500/20"
                      )}>
                        {letter.status === "completed" ? "Ready" : "Generating..."}
                      </span>
                    </div>
                    <div className="flex items-center gap-4">
                      {letter.status === "completed" ? (
                        <>
                          <button className="text-xs font-bold text-white hover:underline flex items-center gap-1.5 uppercase tracking-wide">
                            View Letter <ArrowRight className="w-3.5 h-3.5" />
                          </button>
                          <button className="text-xs font-bold text-[#A1A1AA] hover:text-white flex items-center gap-1.5 uppercase tracking-wide transition-colors">
                            <Download className="w-3.5 h-3.5" /> PDF
                          </button>
                        </>
                      ) : (
                        <span className="text-xs text-[#A1A1AA] uppercase tracking-widest font-bold font-mono">Generating...</span>
                      )}
                      <button 
                        onClick={() => deleteMutation.mutate(letter.id)}
                        className="text-sm font-medium text-red-500 hover:text-red-400 ml-auto opacity-0 group-hover:opacity-100 transition-all p-2 rounded-lg hover:bg-red-500/10"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="p-16 text-center text-[#A1A1AA]">
                <FileText className="w-16 h-16 mx-auto mb-4 opacity-10" />
                <p className="font-bold text-white mb-1">No cover letters yet</p>
                <p className="text-xs uppercase tracking-widest">Generate your first cover letter to start</p>
              </div>
            )}
          </div>
        </div>

        <div className="space-y-6">
          <div className="dash-card p-4">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-lg bg-[#161616] border border-zinc-800 text-white shadow-inner">
                <Sparkles className="w-5 h-5" />
              </div>
              <h3 className="font-bold text-white">AI Tone Tuning</h3>
            </div>
            <p className="text-xs text-[#A1A1AA] mb-6 leading-relaxed">
              Our AI analyzes your selected resume and the target job description to match the company culture perfectly.
            </p>
            <div className="space-y-3">
              {tones.map(t => (
                <div key={t.value} className={cn("flex items-center gap-3 px-4 py-2.5 rounded-xl bg-[#161616] border text-xs font-bold transition-all", selectedTone === t.value ? "border-white text-white shadow-[0_0_10px_rgba(255,255,255,0.05)]" : "border-zinc-800 text-[#A1A1AA]") }>
                   <div className={cn("w-2 h-2 rounded-full transition-all", selectedTone === t.value ? "bg-white shadow-[0_0_8px_#fff]" : "bg-zinc-800")} />
                   <span className="uppercase tracking-widest">{t.label}</span>
                </div>
              ))}
            </div>
          </div>

          {!canAccess("cover_letters") && (
            <div className="dash-card p-6 text-center relative overflow-hidden">
               <div className="absolute top-0 right-0 p-4">
                  <Crown className="w-4 h-4 text-amber-500/30" />
               </div>
               <h4 className="text-sm font-bold mb-2 text-white uppercase tracking-widest">Upgrade to Pro</h4>
               <p className="text-xs text-[#A1A1AA] mb-6 leading-relaxed">Get unlimited cover letters and advanced AI tuning options.</p>
               <button className="w-full py-2.5 bg-white text-black rounded-lg text-xs font-black uppercase tracking-widest shadow-lg hover:bg-gray-200 transition-all">
                 View Plans
               </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
