"use client";
import React, { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { coverLettersApi, jobsApi } from "@/lib/api";
import { useSubscription } from "@/lib/subscription";
import { Sparkles, FileText, Send, Wand2, ArrowRight, BookOpen, Clock, Crown, Download, Eye, Trash2, Plus, X } from "lucide-react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

interface CoverLetter {
  id: string;
  job_id: string;
  job_title?: string;
  company_name?: string;
  tone: string;
  content: string;
  status: string;
  created_at: string;
}

interface Job {
  id: string;
  title: string;
  company_name: string;
}

export default function CoverLettersPage() {
  const { canAccess } = useSubscription();
  const qc = useQueryClient();
  const [showGenerate, setShowGenerate] = useState(false);
  const [selectedJob, setSelectedJob] = useState("");
  const [selectedTone, setSelectedTone] = useState("professional");

  const { data: letters, isLoading } = useQuery({
    queryKey: ["cover-letters"],
    queryFn: () => coverLettersApi.list().then((r) => r.data),
  });

  const { data: jobs } = useQuery({
    queryKey: ["jobs-select"],
    queryFn: () => jobsApi.list({ page: 1, page_size: 50 }).then((r) => r.data.items || []),
    enabled: canAccess("cover_letters"),
  });

  const generateMutation = useMutation({
    mutationFn: (data: { job_id: string; tone: string }) => coverLettersApi.generate(data),
    onSuccess: () => {
      toast.success("Cover letter generation started");
      setShowGenerate(false);
      qc.invalidateQueries({ queryKey: ["cover-letters"] });
    },
    onError: () => {
      toast.error("Failed to start generation");
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => coverLettersApi.delete(id),
    onSuccess: () => {
      toast.success("Cover letter deleted");
      qc.invalidateQueries({ queryKey: ["cover-letters"] });
    },
  });

  const handleGenerate = () => {
    if (!selectedJob) {
      toast.error("Please select a job");
      return;
    }
    generateMutation.mutate({ job_id: selectedJob, tone: selectedTone });
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr) return "Unknown";
    const date = new Date(dateStr);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    if (diffHours < 1) return "Just now";
    if (diffHours < 24) return `${diffHours}h ago`;
    const diffDays = Math.floor(diffHours / 24);
    if (diffDays === 1) return "Yesterday";
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  };

  const tones = [
    { value: "professional", label: "Professional", desc: "Formal & corporate" },
    { value: "casual", label: "Casual", desc: "Friendly & relaxed" },
    { value: "founder", label: "Founder-focused", desc: "Entrepreneurial & bold" },
    { value: "enthusiastic", label: "Enthusiastic", desc: "Energetic & positive" },
  ];

  return (
    <div className="space-y-8 max-w-6xl">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold font-display flex items-center gap-3">
            <BookOpen className="w-8 h-8 text-brand-purple-light" />
            AI Cover Letters
          </h1>
          <p className="text-muted-foreground mt-1 text-lg">
            Personalized, job-specific cover letters generated by LLaMA-70B.
          </p>
        </div>
        {canAccess("cover_letters") && (
          <button 
            onClick={() => setShowGenerate(true)}
            className="px-6 py-3 bg-brand-purple text-white rounded-xl font-bold hover:shadow-xl hover:shadow-brand-purple/40 transition-all flex items-center gap-2"
          >
            <Wand2 className="w-4 h-4" />
            Generate New Letter
          </button>
        )}
      </div>

      {/* Generate Modal */}
      {showGenerate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm">
          <div className="glass-card p-6 w-full max-w-md">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-semibold text-lg">Generate Cover Letter</h3>
              <button onClick={() => setShowGenerate(false)} className="p-1 hover:bg-muted rounded">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="space-y-4">
              <div>
                <label className="text-sm text-muted-foreground mb-2 block">Select Job</label>
                <select 
                  value={selectedJob}
                  onChange={(e) => setSelectedJob(e.target.value)}
                  className="w-full p-3 bg-muted border border-border rounded-lg"
                >
                  <option value="">Choose a job...</option>
                  {jobs?.map((job: Job) => (
                    <option key={job.id} value={job.id}>
                      {job.title} at {job.company_name}
                    </option>
                  ))}
                </select>
              </div>
              
              <div>
                <label className="text-sm text-muted-foreground mb-2 block">Tone</label>
                <div className="grid grid-cols-2 gap-2">
                  {tones.map((tone) => (
                    <button
                      key={tone.value}
                      onClick={() => setSelectedTone(tone.value)}
                      className={cn(
                        "p-3 rounded-lg border text-left text-sm transition-all",
                        selectedTone === tone.value 
                          ? "border-brand-purple bg-brand-purple/10" 
                          : "border-border hover:border-brand-purple/50"
                      )}
                    >
                      <div className="font-medium">{tone.label}</div>
                      <div className="text-[10px] text-muted-foreground">{tone.desc}</div>
                    </button>
                  ))}
                </div>
              </div>
              
              <button 
                onClick={handleGenerate}
                disabled={generateMutation.isPending || !selectedJob}
                className="w-full py-3 bg-brand-purple text-white rounded-lg font-bold disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {generateMutation.isPending ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <Wand2 className="w-4 h-4" />
                )}
                Generate Letter
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-card overflow-hidden">
            <div className="p-6 border-b border-border bg-white/5 flex items-center justify-between">
              <h3 className="font-semibold flex items-center gap-2">
                <Clock className="w-4 h-4 text-brand-purple-light" />
                Your Cover Letters
              </h3>
              <span className="text-xs text-muted-foreground">{letters?.length || 0} letters</span>
            </div>
            {isLoading ? (
              <div className="p-8 text-center">
                <div className="w-6 h-6 border-2 border-brand-purple border-t-transparent rounded-full animate-spin mx-auto" />
              </div>
            ) : letters && letters.length > 0 ? (
              <div className="divide-y divide-border">
                {letters.map((letter: CoverLetter) => (
                  <div key={letter.id} className="p-6 hover:bg-white/5 transition-all group">
                    <div className="flex items-start justify-between mb-4">
                      <div className="flex items-center gap-4">
                        <div className="w-10 h-10 rounded-lg bg-zinc-800 flex items-center justify-center">
                          <FileText className="w-5 h-5 text-muted-foreground" />
                        </div>
                        <div>
                          <h4 className="font-bold text-lg">{letter.job_title || "Job Application"}</h4>
                          <p className="text-sm text-muted-foreground">{letter.company_name || "Company"} • {formatDate(letter.created_at)}</p>
                        </div>
                      </div>
                      <span className={cn(
                        "px-3 py-1 rounded-full text-xs font-bold",
                        letter.status === "completed" ? "bg-emerald-500/10 text-emerald-500" : "bg-amber-500/10 text-amber-500"
                      )}>
                        {letter.status === "completed" ? "Ready" : "Generating..."}
                      </span>
                    </div>
                    <div className="flex items-center gap-4">
                      {letter.status === "completed" ? (
                        <>
                          <button className="text-sm font-medium text-brand-purple-light hover:underline flex items-center gap-1.5">
                            View Letter <ArrowRight className="w-3.5 h-3.5" />
                          </button>
                          <button className="text-sm font-medium text-muted-foreground hover:text-foreground flex items-center gap-1.5">
                            <Download className="w-3.5 h-3.5" /> PDF
                          </button>
                        </>
                      ) : (
                        <span className="text-sm text-muted-foreground">Generating...</span>
                      )}
                      <button 
                        onClick={() => deleteMutation.mutate(letter.id)}
                        className="text-sm font-medium text-red-400 hover:text-red-300 ml-auto opacity-0 group-hover:opacity-100"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="p-8 text-center text-muted-foreground">
                <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
                <p>No cover letters yet</p>
                <p className="text-sm mt-1">Generate your first cover letter</p>
              </div>
            )}
          </div>
        </div>

        <div className="space-y-6">
          <div className="glass-card p-6 bg-brand-purple/5 border-brand-purple/20">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 rounded-lg bg-brand-purple/10 text-brand-purple-light">
                <Sparkles className="w-5 h-5" />
              </div>
              <h3 className="font-bold">AI Tone Tuning</h3>
            </div>
            <p className="text-xs text-muted-foreground mb-4 leading-relaxed">
              Our AI analyzes your selected resume and the target job description to match the company culture perfectly.
            </p>
            <div className="space-y-2">
              {tones.map(t => (
                <div key={t.value} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-zinc-900 border border-border text-xs text-muted-foreground">
                   {selectedTone === t.value && <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />}
                   {t.label}
                </div>
              ))}
            </div>
          </div>

          {!canAccess("cover_letters") && (
            <div className="glass-card p-8 text-center relative overflow-hidden">
               <div className="absolute top-0 right-0 p-4">
                  <Crown className="w-4 h-4 text-amber-500/50" />
               </div>
               <h4 className="text-sm font-bold mb-2">Upgrade to Pro</h4>
               <p className="text-xs text-muted-foreground mb-4">Get unlimited cover letters</p>
               <button className="px-4 py-2 bg-brand-purple text-white rounded text-xs font-bold">
                 View Plans
               </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
