"use client";
import React from "react";
import { Sparkles, FileText, Send, Wand2, ArrowRight, BookOpen, Clock, Crown } from "lucide-react";
import { motion } from "framer-motion";

const letters = [
  { id: 1, job: "Senior AI Engineer", company: "Google", date: "2 hours ago", status: "Ready" },
  { id: 2, job: "Full Stack Developer", company: "Rippling", date: "昨天", status: "Draft" },
  { id: 3, job: "Machine Learning Intern", company: "NVIDIA", date: "3 days ago", status: "Ready" },
];

export default function CoverLettersPage() {
  return (
    <div className="space-y-8 max-w-6xl">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold font-display flex items-center gap-3">
            <BookOpen className="w-8 h-8 text-brand-purple-light" />
            AI Cover Letters
          </h1>
          <p className="text-muted-foreground mt-1 text-lg">
            Personalized, job-specific cover letters generated by LLaMA-70B.
          </p>
        </div>
        <button className="px-6 py-3 bg-brand-purple text-white rounded-xl font-bold hover:shadow-xl hover:shadow-brand-purple/40 transition-all flex items-center gap-2">
          <Wand2 className="w-4 h-4" />
          Generate New Letter
        </button>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-card overflow-hidden">
            <div className="p-6 border-b border-border bg-white/5 flex items-center justify-between">
              <h3 className="font-semibold flex items-center gap-2">
                <Clock className="w-4 h-4 text-brand-purple-light" />
                Recent Generations
              </h3>
            </div>
            <div className="divide-y divide-border">
              {letters.map((letter) => (
                <div key={letter.id} className="p-6 hover:bg-white/5 transition-all group">
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 rounded-lg bg-zinc-800 flex items-center justify-center">
                        <FileText className="w-5 h-5 text-muted-foreground" />
                      </div>
                      <div>
                        <h4 className="font-bold text-lg">{letter.job}</h4>
                        <p className="text-sm text-muted-foreground">{letter.company} • {letter.date}</p>
                      </div>
                    </div>
                    <span className={`px-3 py-1 rounded-full text-xs font-bold ${letter.status === 'Ready' ? 'bg-emerald-500/10 text-emerald-500' : 'bg-zinc-500/10 text-zinc-500'}`}>
                      {letter.status}
                    </span>
                  </div>
                  <div className="flex items-center gap-4">
                    <button className="text-sm font-medium text-brand-purple-light hover:underline flex items-center gap-1.5">
                      View Letter <ArrowRight className="w-3.5 h-3.5" />
                    </button>
                    <button className="text-sm font-medium text-muted-foreground hover:text-foreground">Download PDF</button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="glass-card p-6 bg-brand-purple/5 border-brand-purple/20">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 rounded-lg bg-brand-purple/10 text-brand-purple-light">
                <Sparkles className="w-5 h-5" />
              </div>
              <h3 className="font-bold">AI Tone Tuning</h3>
            </div>
            <p className="text-xs text-muted-foreground mb-4 leading-relaxed">
              Our AI analyzes your selected resume and the target job description to match the company culture perfectly.
            </p>
            <div className="space-y-2">
              {['Professional', 'Casual', 'Founder-focused', 'Enthusiastic'].map(t => (
                <div key={t} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-zinc-900 border border-border text-xs text-muted-foreground">
                   {t === 'Professional' && <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />}
                   {t}
                </div>
              ))}
            </div>
          </div>

          <div className="glass-card p-8 text-center relative overflow-hidden">
             <div className="absolute top-0 right-0 p-4">
                <Crown className="w-4 h-4 text-amber-500/50" />
             </div>
             <h4 className="text-sm font-bold mb-2">Pro Feature Usage</h4>
             <div className="text-3xl font-black mb-1">24/50</div>
             <p className="text-[10px] uppercase tracking-widest text-muted-foreground mb-4">Letters this month</p>
             <div className="w-full h-1 bg-muted rounded-full overflow-hidden">
                <div className="h-full bg-brand-purple" style={{ width: '48%' }} />
             </div>
          </div>
        </div>
      </div>
    </div>
  );
}
